cleaningTab <- 
  fluidPage(
    tags$link(rel = "stylesheet",type = "text/css", href = "style.css"),
    tags$div(class = "clinputtxt",selectInput(inputId = "clinput",label = "ファイル形式を選択",choices = list("csv","xlsx"))),
    tags$div(class = "datauploadvar",fileInput(inputId = "dataupload",label = p("元データ選択"),
              multiple = FALSE,placeholder = "操作する元データをアップロードしてください")),
    tags$hr(),
    uiOutput(outputId = "h3summary"),
    tableOutput(outputId = "cltable"),
    uiOutput(outputId = "clsummary"),
    tags$div(class = "space"),
    tags$hr(),
    uiOutput(outputId = "h3handling"),
    uiOutput(outputId =  "clctrl"),
    uiOutput(outputId = "clctrlui"),
    uiOutput(outputId = "h3option"),
    uiOutput(outputId = "uiclsentaku"),
    uiOutput(outputId = "cleantable1"),
    uiOutput(outputId = "cleantable2"),
    uiOutput(outputId = "cleantable3"),
    uiOutput(outputId = "cleantable4"),
    uiOutput(outputId = "cleantable5"),
    uiOutput(outputId = "cleantable6"), 
    uiOutput(outputId = "cleantable7_1"),
    uiOutput(outputId = "cleantable7"),  
    uiOutput(outputId = "cleantable8"),
    uiOutput(outputId = "cleantable9_1"),
    uiOutput(outputId = "cleantable9"),
    uiOutput(outputId = "cleantable10"),
    uiOutput(outputId = "dw1"),
    uiOutput(outputId = "dw2"),
    uiOutput(outputId = "dw3"),
    uiOutput(outputId = "dw4"),
    uiOutput(outputId = "dw5"),
    uiOutput(outputId = "dw6"),
    uiOutput(outputId = "kigou")
  )
