plotoutputTab <- 
  fluidPage(title = "plotoutput一覧",
            fileInput(inputId = "file1",label = p("file upload"),accept = c("text/csv",
                                                                           "text/comma-separated-values,text/plain",
                                                                           ".csv"),
                      multiple = FALSE,
                      placeholder = "csvファイルを選択"),
            tags$hr(),
            column(width = 3,uiOutput(outputId = "listx")),
            column(width = 3,uiOutput(outputId = "listy")),
            tags$hr(),
            column(width = 4,textOutput(outputId = "tablett"),tableOutput(outputId = "table")),
            column(width = 4,textOutput(outputId = "scattertt"),plotOutput(outputId = "scatterplot")),
            column(width = 4,textOutput(outputId = "histgramtt"),plotOutput(outputId = "histgram")),
            column(width = 4,textOutput(outputId = "boxplottt"),plotOutput(outputId = "boxplot")),
            column(width = 4,textOutput(outputId = "violinolottt"),plotOutput(outputId = "violinplot")),
            column(width = 4,textOutput("heatmaptt"),plotOutput("heatmap")),
            column(width = 4,textOutput("dotplottt"),plotOutput("dotplot")),
            column(width = 4,textOutput("lineplottt"),plotOutput("lineplot")),
            column(width = 4,textOutput("barplottt"),plotOutput("barplot")),
            column(width = 4,textOutput("stackedbarplottt"),plotOutput("stackedbarplot")),
            column(width = 4,textOutput("facetedplottt"),plotOutput("facetedplot")),
            column(width = 4,textOutput("timeseriesplottt"),plotOutput("timeseriesplot")),
            column(width = 4,textOutput("densityplottt"),plotOutput("densityplot")),
            column(width = 4,textOutput("contourplottt"),plotOutput("contourplot")),
            column(width = 4,textOutput("areaplottt"),plotOutput("areaplot")),
            column(width = 4,textOutput("piecharttt"),plotOutput("piechart")),
            column(width = 4,textOutput("volcanoplottt"),plotOutput("volcanoplot"))
            )
