plotoutputTab <- 
  fluidPage(title = "plotoutput一覧",
            tags$link(rel = "stylesheet",type = "text/css", href = "style.css"),
            h2("Plot",class = "cltitle"),
            tags$div(class = "plottitlespace"),
            tags$div(
              class = "plfileinput",
              selectInput(inputId = "filetype",label = "ファイル形式を選択",choices = list(".xlsx",".csv")),
              fileInput(inputId = "file1",label = p("元データ選択"),accept = c("text/csv",
                                                                             "text/comma-separated-values,text/plain",
                                                                             ".csv"),
                        multiple = FALSE,
                      placeholder = "ファイルを選択")),
            tags$hr(),
            tags$div(class = "space"),
            column(width = 3,uiOutput(outputId = "listx")),
            column(width = 3,uiOutput(outputId = "listy")),
            tags$hr(),
            column(width = 4,textOutput(outputId = "tablett"),tableOutput(outputId = "table1")),
            column(width = 4,textOutput(outputId = "scattertt"),plotOutput(outputId = "scatterplot")),
            column(width = 4,textOutput(outputId = "histgramtt"),plotOutput(outputId = "histgram")),
            column(width = 4,textOutput(outputId = "boxplottt"),plotOutput(outputId = "boxplot")),
            column(width = 4,textOutput(outputId = "violinolottt"),plotOutput(outputId = "violinplot")),
            column(width = 4,textOutput("heatmaptt"),plotOutput("heatmap")),
            column(width = 4,textOutput("dotplottt"),plotOutput("dotplot")),
            column(width = 4,textOutput("lineplottt"),plotOutput("lineplot")),
            column(width = 4,textOutput("barplottt"),plotOutput("barplot")),
            column(width = 4,textOutput("stackedbarplottt"),plotOutput("stackedbarplot")),
            column(width = 4,textOutput("densityplottt"),plotOutput("densityplot")),
            column(width = 4,textOutput("contourplottt"),plotOutput("contourplot")),
            column(width = 4,textOutput("areaplottt"),plotOutput("areaplot")),
            column(width = 4,textOutput("piecharttt"),plotOutput("piechart")),
            tags$hr(),
            tags$div(class = "space"),
            div(class = "memotxt",column(width = 12,uiOutput(outputId = "memo")))
            )
