plotoutputTab <- 
  fluidPage(title = "plotoutput一覧",
            fileInput(inputId = "file1",label = p("file upload"),accept = c("text/csv",
                                                                           "text/comma-separated-values,text/plain",
                                                                           ".csv"),
                      multiple = FALSE,
                      placeholder = "csvファイルを選択"),
            tags$hr(),
            column(width = 3,uiOutput(outputId = "listx")),
            column(width = 3,uiOutput(outputId = "listy")),
            tags$hr(),
            column(width = 4,p("datatable"),tableOutput(outputId = "table")),
            column(width = 4,p("scatterplot"),plotOutput(outputId = "scatterplot")),
            column(width = 4,p("histgram"),plotOutput(outputId = "histgram")),
            column(width = 4,p("boxplot"),plotOutput(outputId = "boxplot")),
            column(width = 4,p("violinplot"),plotOutput(outputId = "violinplot")),
            column(width = 4,p("heatmap"),plotOutput("heatmap")),
            column(width = 4,p("dotplot"),plotOutput("dotplot")),
            column(width = 4,p("lineplot"),plotOutput("lineplot")),
            column(width = 4,p("barplot"),plotOutput("barplot")),
            column(width = 4,p("stackedbarplot"),plotOutput("stackedbarplot")),
            column(width = 4,p("facetedplot"),plotOutput("facetedplot")),
            column(width = 4,p("timeseriesplot"),plotOutput("timeseriesplot")),
            column(width = 4,p("densityplot"),plotOutput("densityplot")),
            column(width = 4,p("contourplot"),plotOutput("contourplot")),
            column(width = 4,p("areaplot"),plotOutput("areaplot")),
            column(width = 4,p("piechart"),plotOutput("piechart")),
            column(width = 4,p("labeledplot"),plotOutput("labeledplot")),
            column(width = 4,p("volcanoplot"),plotOutput("volcanoplot"))
            )
