column(width = 4,p(""),plotOutput(outputId = "histgram")),
column(width = 4,p(""),plotOutput(outputId = "boxplot")),
column(width = 4,p(""),plotOutput(outputId = "violinplot")),
column(width = 4,p(""),plotOutput("heatmap")),
column(width = 4,p(""),plotOutput("dotplot")),
column(width = 4,p(""),plotOutput("lineplot")),
column(width = 4,p(""),plotOutput("violinplot")),
column(width = 4,p(""),plotOutput("lineplot")),
column(width = 4,p(""),plotOutput("barplot")),
column(width = 4,p(""),plotOutput("stackedbarplot")),
column(width = 4,p(""),plotOutput("facetedplot")),
column(width = 4,p(""),plotOutput("timeseriesplot")),
column(width = 4,p(""),plotOutput("densityplot")),
column(width = 4,p(""),plotOutput("contourplot")),
column(width = 4,p(""),plotOutput("areaplot")),
column(width = 4,p(""),plotOutput("piechart")),
column(width = 4,p(""),plotOutput("labeledplot")),
column(width = 4,p(""),plotOutput("volcanoplot")
